### ISSUE TITLE
Content phrases support multiple words

### ISSUE THREAD

**Issue by test1964** [andybalholm/redwood#17]
Hey,

For now you support word matching like this(to block page need 100):

    <game>  10
    <sport>  10

If in page the word "game"  count 5 times all ok
if in other page the word "sport" count 2 times all ok
Now I want that if in page there is "game" and also "sport" (other place in page) I want to block it,
how to do it?
This not support :

    <game>,<sport> 150

Thanks

**Comment by andybalholm** [comment]
That is a feature of DansGuardian that we didn't copy in Redwood. There is no way to do exactly the same thing in Redwood.

But you could do something similar by putting a fairly high score on each word, but putting a ceiling on so that it can't block the page by itself:

    <game> 30 90
    <sport> 50 90

Then neither "game" nor sport can block the page by itself, since their scores are limited to 90 points. But if you have both of them on the page, and either one appears twice, it will be blocked.

**Comment by thinkwelltwd** [comment]
>That is a feature of DansGuardian that we didn't copy in Redwood. There is no way to do exactly the same thing in Redwood.

This is not a severe limitation because it's such a naive concept where the disconnected phrases are removed from grammatical significance. In Dansguardian, this technique contributes to false positives more often than accuracy.

Of more significance and sophistication are these Redwood concepts:
1. You can have the same phrases in multiple categories.
2. You can have a score & ceiling, so that a word only contributes to a maximum amount: &lt; sport&gt; 10 90
3. Each category is more than a directory; it is canonical and scored separately from the others.  Dansguardian categories are scored all together

**Comment by test1964** [comment]
Then what to define if < game > and < sport > appear once in the same page and I want it will be blocked?
If < game  >  is 30   and  < sport > is 50 - page will not be blocked (not over 100) , correct?

**Comment by andybalholm** [comment]
If you want it to be blocked with one occurrence of each, you will need to raise the scores so that the sum is greater than 100—say 55 each.

**Comment by thinkwelltwd** [comment]
>Then what to define if < game > and < sport > appear once in the same page and I want it will be blocked?
If < game > is 30 and < sport > is 50 - page will not be blocked (not over 100) , correct?

No, it won't be; that's correct. You can increase the point score of each and then it would. 

Could you elaborate on what's behind this request? Do you have any specific example pages where the only 2 phrases to go on such as "game" and "sport"? A much better approach would be to base your scoring decision on a broad base of phrases with low scores instead of a small number of phrases with high scores.

**Comment by test1964** [comment]
Thanks,
All stuff working very well/
