### ISSUE TITLE
Url rewrite

### ISSUE THREAD

**Issue by test1964** [andybalholm/redwood#18]
Hey ,

In squid for example I used to change  user  url with "URL_Rewrite" so :
when he try to go to "www.google.com" I redirect him to 'bing.com'
How can I do here redirect users ?

**Comment by andybalholm** [comment]
We don't have a general-purpose URL rewriter. You could try `virtual-host`.

    virtual-host google.com bing.com
    virtual-host www.google.com www.bing.com

It only works for HTTP, though, not for HTTPS.

**Comment by test1964** [comment]
Why it not working also in Https (in Http it working very good)?
It can be done?

**Comment by andybalholm** [comment]
Actually, it might work if the hostname you are spoofing actually exists. I haven't tried it that way.

**Comment by test1964** [comment]
I checked and it not working, maybe need to fix in code?

**Comment by thinkwelltwd** [comment]
>I checked and it not working, maybe need to fix in code?

Virtual hosts weren't intended to be URL rewriters. If it works for that, great. But if it doesn't work, there's still nothing to "fix".

Could you elaborate on why you need this? Is there a reason to redirect google.com to bing?

**Comment by test1964** [comment]
I build my own search engine (based on bing api) and want to force my users to use it (even if they type on chrome address bar some words and this  send it to google search)

**Comment by thinkwelltwd** [comment]
Well, that's an understandable use-case. I don't know how you'd handle other google searches such as Gmail / Maps / Oauth, but that's not part of the question.

Since Redwood doesn't support that, I suppose you could block google.com, and in the block page display a URL to your custom search engine. Wouldn't be elegant, but neither would the users misunderstand your intentions.

**Comment by test1964** [comment]
Thanks,
will check it.
