### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by stern0m1** [andybalholm/redwood#23]
Hi,
I am having trouble configuring redwood for https.
For every https request the logs show:
2017-09-28 19:11:27,192.168.1.59,,,"error reading client hello: expected content type of 22, got 67",
What is content type 67? Any ideas?

Thanks

**Comment by andybalholm** [comment]
67 is the ASCII code for the letter C. I'm pretty sure that the C is the first letter of CONNECT. Redwood is receiving an HTTP CONNECT request instead of a raw TLS connection. So most likely you have the client configured to use your `transparent-https` port in its HTTPS proxy settings. When you're explicitly using a proxy (rather than transparently intercepting), you should use the same port for HTTPS as for HTTP.

**Comment by stern0m1** [comment]
Hey, 
Thanks for you quick response. You where correct. I thought i was supposed to use the transparent port...
