### ISSUE TITLE
Build and install instructions?

### ISSUE THREAD

**Issue by unixabg** [andybalholm/redwood#3]
Greetings,
I am new to golang and could you provide a set of build instructions?

I tried the following:

export GOPATH=/path/to/git-checkout-of/redwood/
go get ./

Then I got:
go install: no install location for directory /home/Code-Work/redwood outside GOPATH
	For more details see: go help gopath

Not sure how to proceed. Please advise.

**Comment by andybalholm** [comment]
You're making it too complicated. I usually set GOPATH to $HOME, so that installed binaries end up in $HOME/bin. If you don't want to do that, create an empty folder somewhere and point GOPATH to it. Then do `go get github.com/andybalholm/redwood`. It will create the directory structure it needs, download Redwood and its dependencies, and compile it. The resulting binary will be in $GOPATH/bin.

**Comment by unixabg** [comment]
Greetings,
First thank you for the timely response. Also I am running go version go1.5.1 linux/amd64 on Jessie. I set GOPATH   "export GOPATH=$HOME/scratch-redwood/"  and below is what I get when I run go get command:

go get github.com/andybalholm/redwood
# github.com/andybalholm/redwood
src/github.com/andybalholm/redwood/transport.go:30: unknown http.Transport field 'ExpectContinueTimeout' in struct literal
src/github.com/andybalholm/redwood/transport.go:42: unknown http.Transport field 'ExpectContinueTimeout' in struct literal

Any ideas?

**Comment by andybalholm** [comment]
Redwood requires Go 1.6 now that I've added HTTP/2 support.

**Comment by unixabg** [comment]
Greetings,
I downloaded Go 1.6 and it compiled :) If I have questions is the issue tracker the best way to communicate questions?

Thanks again for the timely responses and assistance.

**Comment by andybalholm** [comment]
It's probably easier to email directly. My address is andy@balholm.com.
