### ISSUE TITLE
Redirect all outgoing traffic through redwood

### ISSUE THREAD

**Issue by miheerdew** [andybalholm/redwood#42]
I want to setup redwood so that it transparently filters all the outgoing traffic on my mac.  

For my attempt, I copied the [default configuration](https://github.com/andybalholm/redwood-config) and (I hope correctly) created the root certificate and key. After this, redwood was run as user `nobody` and the firewall (PF) was configured to redirect all outgoing traffic not arising from user `nobody` to the redwood ports.  

This configuration works for http, but for each https request the redwood logs show something like:

```2018-03-14 02:34:03.817397,192.168.1.6,,127.0.0.1:6510,infinite redirect loop```
 
Here is the PF configuration file I am using. 
```
rdr pass inet proto tcp from any to any port = 80 -> 127.0.0.1 port 6502
rdr pass inet proto tcp from any to any port = 443 -> 127.0.0.1 port 6510
pass out route-to (lo0 127.0.0.1) inet proto tcp from any to any port = 80 user != nobody 
pass out route-to (lo0 127.0.0.1) inet proto tcp from any to any port = 443 user != nobody
```
These config-rules user a workaround mentioned [here](https://serverfault.com/questions/709369/pf-mac-os-x-rule-to-redirect-all-traffic-to-a-specific-ip-port) because the redirect command only applies to incoming traffic, but that may or may not be very relevant here. 

Even without going into the specific details, would such an approach work?   

**EDIT**: By the way, awesome project :)

**Comment by andybalholm** [comment]
It looks plausible, but I'm not an expert on the pf firewall.

**Comment by miheerdew** [comment]
OK, but do you know why there is an `infinite redirect loop` message?
The [line](https://github.com/andybalholm/redwood/blob/5ddbc655b6d5a7929ede4b07b3a7fc012cf5bc72/transparent.go#L68) may be responsible.

**Comment by andybalholm** [comment]
Right. If Redwood tries to intercept a connection to itself, it keeps intercepting the same connection until it runs out of memory or some other resource. So this error keeps that from happening.

**Comment by miheerdew** [comment]
So, to redirect machines own traffic through redwood, should I remove that line?

**Comment by andybalholm** [comment]
I don't really understand why that's triggering, since it's the source address rather than the destination address that is local. But you could actually remove the whole part about trying to find the original destination address. If Redwood can't get the original destination address from the firewall, it falls back to using the SNI from the TLS client hello. That works for most clients newer than Windows XP.

**Comment by miheerdew** [comment]
With what I am doing (the `route-to` command in PF), the firewall changes the destination address and port of each packet to `127.0.0.1:6510`, so this is expected. But does redwood have a mechanism to get the original address from firewall or is there a better way to redirect https traffic transparently?

**Comment by andybalholm** [comment]
That explains the problem then. If you use `rdr` instead of `route-to`, the destination address is preserved. The syntax (and the location in the config file) is somewhat different, though. See the example in the README.

I'm not sure that `rdr` is available in all versions of pf, but it worked on the FreeBSD system I tested it on.

**Comment by miheerdew** [comment]
Thanks! Nevermind, but I realized that it will be simpler to run redwood as a regular (non-transparent) proxy. I just have to use PF to block all outgoing connection from the non-redwood user. More details are written [here](https://github.com/miheerdew/delayed-admin/wiki/Configuring-Redwood-on-MacOS).
