### ISSUE TITLE
Further development in redwood-config categories

### ISSUE THREAD

**Issue by phuongvietvu0306** [andybalholm/redwood#49]
Thank you for this project for I have used much of your work in my production.
I am wondering how you came up with the result in redwood-config categories?
I would like to develop url and web content classification base on this project and make it more accurate by doing it automatically. Do you suggest any idea to do so?
I am currently doing it manually but I don't know what keywords or phrases would be suitable to add, how many points to give and it is time consuming doing it this way. 

Thank you

**Comment by andybalholm** [comment]
The rules in the redwood-config project are mostly based on the default configuration from DansGuardian (the web filtering program we used before we developed Redwood). 

I've experimented some with machine-learning approaches for building phraselists, but I haven't gotten very far. The biggest obstacle is the huge corpus of correctly-classified pages you'd need in order to train a decently accurate model.

For the ruleset we use in production, all the changes are manual. Basically we find a page that is mis-classified, and adjust the scores of the existing phrases and/or add new phrases to give it more points in the category it should be in.

**Comment by user1121114685** [comment]
Hello, I am the author of koolproxyR, I am very glad to meet you, I am trying to rebuild kool proxyR but I don't have any network filtering software programming foundation, I want to learn through your project, and then maybe use it in some places or roughly the same  The method rebuilds the program, so I want to get your authorization. I didn't start building. It may take a year to learn. When I start building, I will give my thoughts and some useful ideas to you, just like  Debian and Ubuntu, of course I will also open source my project, when I started doing it.  Can you allow me to use some of the code and ideas for your project?  thank.

**Comment by andybalholm** [comment]
Redwood is open-source, with a BSD license. You're free to use code from it as long as you follow the conditions in the LICENSE file.
