### ISSUE TITLE
Logfile does not show real request?

### ISSUE THREAD

**Issue by HiranChaudhuri** [andybalholm/redwood#59]
I am pretty new to redwood so I am still trying to understand the mechanism. While doing that I stumble over the effect that one client request is printed to the log in a (for me) strange way:

This is the request my client is running:
`curl --proxy http://proxy:18081 https://www.youtube.com`

In the logfile I can see entries like this:
`2021-02-26 15:18:59.682487,192.168.178.68,allow,http://www.youtube.com:443,CONNECT,0,,0,,youtube.com 1,"localbump 500, youtube 7",youtube,,,,HTTP/1.1,,`

So if the client requests some HTTPS URL, why does redwood understand HTTP?

**Comment by andybalholm** [comment]
The way HTTPS proxies work (not just Redwood, but the spec) is kind of strange. The client makes a plain HTTP (not HTTPS) connection to the proxy, and sends a request with the CONNECT method (instead of GET or POST like a regular HTTP request), just specifying what server it wants to connect to, not the whole URL.

Then the proxy makes a connection to the origin sever, and just passes all the data straight through with no processing. At least, that's what normally happens; Redwood can intercept the connection instead (ssl-bump), and then you'll see the actual HTTPS requests as well. But this log line shows an action of "allow", not "ssl-bump", so we know that Redwood didn't intercept the connection.

**Comment by hiranchaudhuri1** [comment]
Thank you for the explanation. I agree this was an allow and I want to test ssl-bump in my next step.
All I was confued about was the HTTP label. If redwood just creates a TCP connection and forwards outgoing and incoming data, maybe then HTTP should be either omitted or replaced by TCP?

I found it confusing since HTTP would indicate there is no encryption although the port 443 is used (a port per se does not mandate encryption).

**Comment by andybalholm** [comment]
No matter how we log CONNECT requests, they will need to be treated specially when analyzing the log files, because they *are* special.

**Comment by HiranChaudhuri** [comment]
So we do agree it does not matter how CONNECT requests are logged? 
To users unfamiliar with Redwood it may make a difference. Redwood just connects via TCP, and it does not care whether inside there is HTTP, HTTPS, FTP, or any other protocol. In my eyes logging anything different than TCP is more misleading that helping.
Hence all i want to suggest is to change a log message format.

**Comment by andybalholm** [comment]
The only change that would make sense to me would be to remove the schema completely. I would be in favor of doing that, except…

We need to consider compatibility with existing logfile analysis tools for Redwood. It is quite likely that making that change would break those tools, for almost no gain.

**Comment by HiranChaudhuri** [comment]
That is a nasty dependency.
Maybe some documentation might help in that case - at least for the novice users like me...

**Comment by thinkwelltwd** [comment]
> That is a nasty dependency.

First of all, what dependency are you referring to?  After that, what about it is nasty?

**Comment by HiranChaudhuri** [comment]
Well you mention compatibility to other tools. It seems there is some kind of relation to tools unknown from this project.
Do you know which tools there are? How many? Are they under your control?
If you cannot change them but have to stay compatible, that's what I'd call a nasty dependency.

**Comment by andybalholm** [comment]
The only one I know about is our proprietary graphical console for Redwood, written by @thinkwelltwd. But there may be others. Obviously @thinkwelltwd could change his to handle whatever change I make. But *needing* to change it raises the bar somewhat on how beneficial a change needs to be before it's worth making.

And what about all the users we *don't* know about? That's one of the pains of running an open-source project. People you've never heard of are depending on your code.

**Comment by thinkwelltwd** [comment]
Redwood is an open-source project; graciously given to the world; a Thank You for that would be in order, although not required for use.

> It seems there is some kind of relation to tools unknown from this project.

 Currently this project has 23 forks and 140 stars. Nobody knows if you or anyone else wrote tools for this project.

> If you cannot change them but have to stay compatible...

Github is loaded with projects that changed quickly, and the issue threads are full of indignant people complaining that compatibility wasn't respected.

**Comment by HiranChaudhuri** [comment]
I did not want to blame anyone here, and I am aware there is no money that I could ask back from anyone.
Just wanted to give some constructive comment about something that I stumbled upon, hoping to allow redwood to become even better.

It is for some reason that I found the software and decided it worth to spend time with. ;-)

**Comment by andybalholm** [comment]
By the way, the documentation *does* have a lot of room for improvement. The README is just an updated version of a design document that was written before the software was. Probably the biggest contribution users could make would be well-written documentation that explains the "how" and "why", not just "what".
